test process

diff --git a/.github/workflows/test-wf.yml b/.github/workflows/test-wf.yml
--- a/.github/workflows/test-wf.yml
+++ b/.github/workflows/test-wf.yml
@@ -17,7 +17,7 @@ jobs:
     name: Resources Plan Validation
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
-
+   
     env:
       FOO: '$FOO'
       ENV: ${{ inputs.environment }}
@@ -26,6 +26,11 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v3
+
+      - name: Process
+        if: ${{ vars.process }} == 'true'
+        run: |
+          echo "Process:" ${{ vars.process }}
 
       - name: View Secrets Context
         shell: bash
@@ -36,5 +41,30 @@ jobs:
           # echo "instance:" ${{ env.ENV }}
           echo "server:" ${{ secrets.server }} | sed 's/./& /g'
           # echo "server:" ${{ env.SERVER }}
+
+  check-step:
+    name: Check Process Step
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    needs: azure-login
+
+    steps:
+      - name: Process
+        if: ${{ vars.process }} != 'true'
+        run: |
+          echo "Process Failed:" ${{ vars.process }}
+          exit 1
+
+  re-process-step:
+    name: Re-Process Step
+    runs-on: ubuntu-latest
+    environment: ${{ inputs.environment }}
+    needs: check-step
+    if: ${{ vars.process }} == 'true'
+
+    steps:
+      - name: Process        
+        run: |
+          echo "Re-Process Step:" ${{ vars.process }}          
           
         
